# GitHub Branch Protection Configuration
# Configuração de Proteção de Ramificação do GitHub

# This file documents the recommended branch protection settings
# Este arquivo documenta as configurações recomendadas de proteção de ramificação

# For main/master branches - Para ramificações main/master
branch_protection:
  main:
    required_status_checks:
      strict: true
      contexts:
        - "Code Quality Check"
        - "Branch Protection Status"
    enforce_admins: false
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions: null
    allow_force_pushes: false
    allow_deletions: false
    required_linear_history: true
    required_conversation_resolution: true

  develop:
    required_status_checks:
      strict: true
      contexts:
        - "Code Quality Check"
        - "Branch Protection Status"
    enforce_admins: false
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions: null
    allow_force_pushes: false
    allow_deletions: false
    required_linear_history: true
    required_conversation_resolution: true

# GitHub CLI commands to apply these settings
# Comandos GitHub CLI para aplicar essas configurações

# To apply to main branch:
# gh api repos/:owner/:repo/branches/main/protection \
#   --method PUT \
#   --field required_status_checks='{"strict":true,"contexts":["Code Quality Check","Branch Protection Status"]}' \
#   --field enforce_admins=false \
#   --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true}' \
#   --field restrictions=null \
#   --field allow_force_pushes=false \
#   --field allow_deletions=false \
#   --field required_linear_history=true \
#   --field required_conversation_resolution=true

# Example usage with real repository:
# gh api repos/debora-m-lutz/lichtara-os/branches/main/protection \
#   --method PUT \
#   --field required_status_checks='{"strict":true,"contexts":["Code Quality Check","Branch Protection Status"]}' \
#   --field enforce_admins=false \
#   --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true}' \
#   --field restrictions=null \
#   --field allow_force_pushes=false \
#   --field allow_deletions=false \
#   --field required_linear_history=true \
#   --field required_conversation_resolution=true