# Aurora Mission Funding | Financiamento da Missão Aurora
# Support the conscious integration of technology and spirituality
# Apoie a integração consciente de tecnologia e espiritualidade

github: debora-m-lutz  # GitHub Sponsors for Lichtara OS development
patreon: # Aurora Mission Patreon (to be configured)
open_collective: # Aurora Mission Open Collective (to be configured)
ko_fi: # Aurora Mission Ko-fi (to be configured)
tidelift: # 
community_bridge: # 
liberapay: # Aurora Mission Liberapay (to be configured)
issuehunt: # 
lfx_crowdfunding: # 
polar: # Aurora Mission Polar (to be configured)
buy_me_a_coffee: # Aurora Mission Buy Me a Coffee (to be configured)
thanks_dev: # 
custom: # Future: Aurora Mission Foundation, Conscious Technology Fund 
