# Funding Options for Lichtara OS - Conscious Technology Integration

github: [debora-m-lutz]
patreon: lichtara-os
open_collective: lichtara-os
ko_fi: lichtaraos
tidelift: npm/lichtara-os
community_bridge: lichtara-os
liberapay: lichtara-os
issuehunt: debora-m-lutz/lichtara-os
lfx_crowdfunding: lichtara-os
polar: lichtara-os
buy_me_a_coffee: lichtaraos
thanks_dev: lichtara-os
custom: ["https://lichtara.os/funding", "mailto:funding@lichtara.os", "https://lichtara.os/enterprise", "https://lichtara.os/partnerships"] 
