name: Documentation Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  documentation-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check README exists
      run: |
        if [ ! -f README.md ]; then
          echo "❌ README.md not found"
          exit 1
        fi
        echo "✅ README.md found"
    
    - name: Check for broken links in markdown files
      run: |
        # Find all markdown files and check for potential issues
        find . -name "*.md" -not -path "./.git/*" | while read file; do
          echo "Checking $file..."
          # Basic checks for markdown structure
          if grep -q "^# " "$file"; then
            echo "✅ $file has proper heading structure"
          else
            echo "⚠️  $file might be missing main heading"
          fi
        done
    
    - name: Validate directory structure
      run: |
        # Ensure key directories exist
        directories=("01-fundamentos" "02-manual-aurora" "03-tecnica" "04-legal" "05-ai")
        for dir in "${directories[@]}"; do
          if [ -d "$dir" ]; then
            echo "✅ Directory $dir exists"
          else
            echo "⚠️  Directory $dir not found"
          fi
        done
    
    - name: Check for required files
      run: |
        required_files=("CODE_OF_CONDUCT.md" "CONTRIBUTING.md" ".gitignore")
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file exists"
          else
            echo "❌ Required file $file is missing"
            exit 1
          fi
        done